### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded when having lots of points per tile

### ISSUE THREAD

**Issue by saleiva** [CartoDB/d3.cartodb#173] opened 2016-04-26 15:55 UTC
Looks like when having tons of points per tile the engine/widgets are not working.
You can test with this dataset https://team.cartodb.com/u/saleiva/tables/graffiti_311_sf_8

<img width="525" alt="screen shot 2016-04-26 at 17 53 18" src="https://cloud.githubusercontent.com/assets/132149/14824881/d74a05f4-0bd7-11e6-99b9-a39804ac3cce.png">

**Comment by fdansv** [comment] 2016-04-26 16:00
Probable duplicate of https://github.com/CartoDB/Windshaft-cartodb/issues/427 . Basically Windshaft is not returning all the columns needed to render the map. Same error, started appearing recently with the optimisation that returns just enough columns.

**Comment by rochoa** [comment] 2016-05-03 10:50
We fixed the issue with the tiler not returning columns for dataviews: https://github.com/CartoDB/Windshaft-cartodb/pull/432.

Sorry but I'm a bit lost here: how a missing column in the geojson properties can raise that kind of error in crossfilter?

**Comment by fdansv** [comment] 2016-05-03 10:58
As far as I know (maybe a bug, maybe out of design), creating a dimension in crossfilter from a field that doesn't exist makes the internal `quicksort` method to call itself ad infinitum, provoking the exception.

Crossfilter acts in mysterious ways, I suppose.

In any case, this error doesn't exist anymore, as now the filter will raise an `Error: Couldn't create dimension. Column doesn't exist.` before reaching crossfilter.

**Closed as completed by fdansv** 2016-05-03 10:58 UTC
Labels: bug
